version = 2

root = "/var/lib/containerd"
state = "/run/containerd"
oom_score = 0

disabled_plugins = []

[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0

#[debug]
#  address = "/run/containerd/debug.sock"
#  uid = 0
#  gid = 0
#  level = "info"

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "registry.k8s.io/pause:3.2"
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
        SystemdCgroup = true
  [plugins."io.containerd.runtime.v2.task"]
    platforms = ["linux/arm64"]
