controller:
  ingressClassResource:
    name: nginx
    default: true
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.30.1.80,2600:1700:5010:466a::1:80
    ipFamilyPolicy: "PreferDualStack"
    ipFamilies:
      - IPv4
      - IPv6
    type: LoadBalancer
