---
all:
  vars:
    ansible_user: pi
  children:
    nodes:
      children:
        control_plane_nodes:
          hosts:
            rpi-70-4b.local:
              ansible_host: 172.30.0.70
        worker_nodes:
          hosts:
            rpi-71-4b.local:
              ansible_host: 172.30.0.71
            rpi-72-4b.local:
              ansible_host: 172.30.0.72
            rpi-73-4b.local:
              ansible_host: 172.30.0.73
            rpi-74-4b.local:
              ansible_host: 172.30.0.74
            # rpi-75-3bp.local:
            # rpi-76-3b2.local:
            # rpi-77-3b2.local:
            # rpi-78-3b2.local:
    sensehat_nodes:
      hosts:
        # rpi-75-3bp.local:
