---
all:
  vars:
    ansible_user: pi
  children:
    nodes:
      hosts:
        rpi-70-4b.local:
        rpi-75-3bp.local:
        rpi-76-3b2.local:
        rpi-77-3b2.local:
        rpi-78-3b2.local:
    master_nodes:
      hosts:
        rpi-70-4b.local:
    sensehat_nodes:
      hosts:
        rpi-75-3bp.local:
