---
- name: containerd Container Runtime (CRI)
  hosts: nodes
  become: yes
  tasks:
    # System packages to allow APT repository access over HTTPS
    - name: Dependencies
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest

    - name: Docker APT key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker.gpg

    - name: Docker APT repository
      apt_repository:
        repo: deb [arch=arm64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

    - name: containerd
      apt:
        update_cache: yes
        name:
          - containerd.io
      notify: Restart containerd

    - name: containerd config.toml file
      ansible.builtin.copy:
        src: root/etc/containerd/config.toml
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: "0644"
      notify: Restart containerd

    - name: containerd sandbox_image
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: "^    sandbox_image ="
        line: '    sandbox_image = "registry.k8s.io/pause:3.9"'
        owner: root
        group: root
        mode: "0644"
      notify: Restart containerd

  handlers:
    - name: Restart containerd
      ansible.builtin.service:
        name: containerd.service
        state: restarted
