---
- name: Kubernetes packages
  hosts: nodes
  become: yes
  tasks:
    - name: Ensure /etc/apt/keyrings/ directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Kubernetes APT key
      apt_key:
        url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key"
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Kubernetes APT repository
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /

    - name: Update apt cache
      apt:
        update_cache: yes

    # System packages to allow APT repository access over HTTPS
    - name: Dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: latest

    - name: kubeadm
      apt:
        allow_change_held_packages: yes
        allow_downgrade: yes
        name:
          - "kubeadm={{ kubeadm_version }}"

    - name: Hold kubeadm
      dpkg_selections:
        name: kubeadm
        selection: hold

    - name: kubelet
      apt:
        allow_change_held_packages: yes
        allow_downgrade: yes
        name:
          - "kubelet={{ kubelet_version }}"

    - name: Hold kubelet
      dpkg_selections:
        name: kubelet
        selection: hold

    - name: cri-tools
      apt:
        name:
          - cri-tools

    - name: kubectl
      apt:
        allow_change_held_packages: yes
        allow_downgrade: yes
        name:
          - "kubectl={{ kubectl_version }}"

    - name: Hold kubectl
      dpkg_selections:
        name: kubectl
        selection: hold
