---
- name: Kubernetes node configuration
  hosts: nodes
  become: yes
  tasks:
    - name: Enable IPv6 forwarding - default network interface
      ansible.posix.sysctl:
        name: net.ipv6.conf.default.forwarding
        value: "1"
        sysctl_set: true

    - name: Enable IPv6 forwarding - all network interfaces
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: "1"
        sysctl_set: true

    - name: Accept IPv6 Router Advertisements - default network interface
      ansible.posix.sysctl:
        name: net.ipv6.conf.default.accept_ra
        value: "2"
        sysctl_set: true

    - name: Accept IPv6 Router Advertisements - all network interfaces
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.accept_ra
        value: "2"
        sysctl_set: true

    - name: lh-nas01.local entry in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "{{ item }}$"
        line: "{{ hostvars[item]['ansible_host'] }}     {{ item }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ groups['all'] }}"

    - name: Node static entries in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "lh-nas01.local$"
        line: "172.30.0.10     lh-nas01.local"
        owner: root
        group: root
        mode: "0644"

    - name: Kubernetes kernal modules file
      ansible.builtin.copy:
        src: root/etc/modules-load.d/k8s.conf
        dest: /etc/modules-load.d/k8s.conf
        owner: root
        group: root
        mode: "0644"
      notify: Reboot

    - name: Kubernetes sysctl params modules file
      ansible.builtin.copy:
        src: root/etc/sysctl.d/k8s.conf
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: "0644"
      notify: Reboot

    - name: Kubernetes /boot/cmdline.txt features
      replace:
        path: /boot/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_items:
        - "cgroup_enable=cpuset"
        - "cgroup_enable=memory"
        - "cgroup_memory=1"
        - "swapaccount=1"
      notify: Reboot

    - name: SWAP disabled
      ansible.builtin.service:
        name: dphys-swapfile
        enabled: no
        state: stopped
      notify:
        - Disable SWAP
        - Reboot

  handlers:
    - name: Disable SWAP
      shell: |
        dphys-swapfile swapoff
        dphys-swapfile uninstall

    - name: Configure crictl
      ansible.builtin.copy:
        src: root/etc/crictl.yaml
        dest: /etc/crictl.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Reboot
      reboot:
