---
- name: Kubernetes packages
  hosts: nodes
  become: yes
  tasks:
    # System packages to allow APT repository access over HTTPS
    - name: Dependencies
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: latest

    - name: Google Cloud APT key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

    - name: Kubernetes APT repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main

    - name: kubeadm
      apt:
        update_cache: yes
        allow_change_held_packages: yes
        allow_downgrade: yes
        name:
          - "kubeadm={{ kubeadm_version }}"

    - name: Hold kubeadm
      dpkg_selections:
        name: kubeadm
        selection: hold

    - name: kubelet
      apt:
        update_cache: yes
        allow_change_held_packages: yes
        allow_downgrade: yes
        name:
          - "kubelet={{ kubelet_version }}"

    - name: Hold kubelet
      dpkg_selections:
        name: kubelet
        selection: hold

    - name: kubectl
      apt:
        update_cache: yes
        allow_change_held_packages: yes
        allow_downgrade: yes
        name:
          - "kubectl={{ kubectl_version }}"

    - name: Hold kubectl
      dpkg_selections:
        name: kubectl
        selection: hold
